### ISSUE TITLE
Add 'filebeat' subdirectory to repo root

### ISSUE THREAD

**Issue by whiteinge** [saltstack-formulas/filebeat-formula#1]
In order for this formula to work with GitFS or Salt's `file_roots` the state files need to live under a `filebeat` subdirectory. More explanation at the link below:

https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#repository-structure

**Comment by cybacolt** [comment]
gotcha.

fixed in https://github.com/saltstack-formulas/filebeat-formula/commit/1040493661daa00259427c4545a60ba2f33a5bd5

closing now.

**Comment by whiteinge** [comment]
:+1:
